using Pkg
Pkg.add("Distributed")
Pkg.add("POMDPs")
Pkg.add("POMCPOW")
Pkg.add("Plots")
Pkg.add("Parameters")
Pkg.add("Statistics")
Pkg.add("Random")
Pkg.add("Distributions")
Pkg.add("MineralExploration")
Pkg.add("MixedFidelityModelSelection")
Pkg.add("ProgressMeter")
Pkg.add("BSON")
